#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Apr 20 17:01:54 +03 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1a7e8d0b912c4c44954b37280ebf4334 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tracer_rv32i_soc_tb_behav xil_defaultlib.tracer_rv32i_soc_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1a7e8d0b912c4c44954b37280ebf4334 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tracer_rv32i_soc_tb_behav xil_defaultlib.tracer_rv32i_soc_tb xil_defaultlib.glbl -log elaborate.log

